---

- hosts: all
  become: true
  tasks:

  - name: install pip3, python3 and Java open-jdk for Ubuntu
    apt:
      name:
        - python3
        - python3-pip
        - openjdk-11-jdk
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install pip3, python3 and Java open-jdk for CentOS
    dnf:
      name:
        - python3
        - python3-pip
        - java-1.8.0-openjdk
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
