FROM ubuntu
MAINTAINER jozshua<qjaaalonzo@tip.edu.ph>

# skip interactions
ARG DEBIAN_FRONTEND=noneinteractive

# update packages
RUN apt update; apt dist-upgrade -y

# install packages
RUN apt install -y apache2 mariadb-server

# set entrypoint
ENTRYPOINT apache2ctl -D FOREGROUND
